blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/Losses/rune/blob/master/CONTRIBUTING.md#features
    about: As Rune is in its early development phase, we are not accepting feature requests.
